#!/usr/bin/env bash
#
# install.sh — Install Copilot skills into a target repository.
#
# Usage:
#   ./install.sh --target /path/to/repo
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFEST_FILE="$SCRIPT_DIR/manifest.json"

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------
TARGET="."

# ---------------------------------------------------------------------------
# Parse arguments
# ---------------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --target)
      TARGET="$2"
      shift 2
      ;;
    -h|--help)
      echo "Usage: $0 [--target path]"
      echo ""
      echo "Options:"
      echo "  --target   Target repository path (default: current directory)"
      echo "  -h, --help Show this help message"
      exit 0
      ;;
    *)
      echo "Error: Unknown option '$1'"
      echo "Run '$0 --help' for usage information."
      exit 1
      ;;
  esac
done

# ---------------------------------------------------------------------------
# Resolve paths
# ---------------------------------------------------------------------------
TARGET="$(cd "$TARGET" && pwd)"
SKILLS_DEST="$TARGET/.github/skills"

# Read version from manifest
VERSION="unknown"
if [[ -f "$MANIFEST_FILE" ]]; then
  VERSION=$(python3 -c "import json; print(json.load(open('$MANIFEST_FILE'))['version'])" 2>/dev/null || echo "unknown")
fi

INSTALL_DATE="$(date +%Y-%m-%d)"

echo "============================================"
echo " Copilot Skills Installer v${VERSION}"
echo "============================================"
echo ""
echo "Target:  $TARGET"
echo "Date:    $INSTALL_DATE"
echo ""

# ---------------------------------------------------------------------------
# Validation helpers
# ---------------------------------------------------------------------------
WARNINGS=0
ERRORS=0

validate_skill_file() {
  local skill_file="$1"
  local skill_dir
  skill_dir="$(dirname "$skill_file")"

  # Validate SKILL.md frontmatter has required fields
  local frontmatter
  frontmatter=$(awk '/^---$/{if(++c==2) exit} c' "$skill_file")

  for field in name description allowed-tools; do
    if ! echo "$frontmatter" | grep -q "^${field}:"; then
      echo "  ERROR: $skill_file is missing required frontmatter field: $field"
      ERRORS=$((ERRORS + 1))
    fi
  done

  # Check REFERENCE.md exists alongside SKILL.md
  if [[ ! -f "$skill_dir/REFERENCE.md" ]]; then
    echo "  ERROR: $skill_dir/ is missing REFERENCE.md"
    ERRORS=$((ERRORS + 1))
  fi

  # Warn if SKILL.md exceeds 300 lines
  local line_count
  line_count=$(wc -l < "$skill_file" | tr -d ' ')
  if [[ "$line_count" -gt 300 ]]; then
    echo "  WARNING: $skill_file is $line_count lines (exceeds 300-line threshold)"
    WARNINGS=$((WARNINGS + 1))
  fi
}

# ---------------------------------------------------------------------------
# Copy skills
# ---------------------------------------------------------------------------
echo "--- Installing skills ---"

if [[ -d "$SCRIPT_DIR/skills" ]]; then
  mkdir -p "$SKILLS_DEST"
  cp -R "$SCRIPT_DIR/skills/"* "$SKILLS_DEST/" 2>/dev/null || true
  echo "  Copied skills/* -> $SKILLS_DEST/"

  # Validate each skill (SKILL.md files may be in platform subdirs)
  while IFS= read -r -d '' skill_file; do
    validate_skill_file "$skill_file"
  done < <(find "$SCRIPT_DIR/skills" -name 'SKILL.md' -print0 2>/dev/null || true)
else
  echo "  WARNING: skills/ directory not found, skipping."
  WARNINGS=$((WARNINGS + 1))
fi

echo ""

# ---------------------------------------------------------------------------
# Generate MANIFEST.md
# ---------------------------------------------------------------------------
echo "--- Generating MANIFEST.md ---"

cat > "$SKILLS_DEST/MANIFEST.md" <<EOF
# Installed Copilot Skills

- **Version:** ${VERSION}
- **Installed on:** ${INSTALL_DATE}
- **Source:** copilot-skills

---
*Generated by install.sh*
EOF

echo "  Created $SKILLS_DEST/MANIFEST.md"
echo ""

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo "============================================"
echo " Installation complete"
echo "============================================"
echo "  Errors:   $ERRORS"
echo "  Warnings: $WARNINGS"
echo ""

if [[ "$ERRORS" -gt 0 ]]; then
  echo "There were validation errors. Please fix them before committing."
  exit 1
fi

if [[ "$WARNINGS" -gt 0 ]]; then
  echo "There were warnings. Review them above."
fi

exit 0
